# -*- coding: UTF-8 -*-
# **********************************************************************************#
#     File: Pattern file.
# **********************************************************************************#
import re


SYMBOL_PATTERN_STOCK = '[036]\d{5}\.(XSHE|XSHG)'
SYMBOL_PATTERN_BASE_FUTURES = '[A-Z]{1,2}\d{3,4}$'
SYMBOL_PATTERN_FUTURE_PRODUCT = '^[A-Z]{1,2}'
SYMBOL_PATTERN_CONTINUOUS_FUTURES = '[A-Z]{1,2}(M0|M1|N0|N1|P0|P1|L0|L1|L3|L6)$'
SYMBOL_PATTERN_INDEX = '(\d{6}.ZICN|000\d{3}.XSHG|399\d{3}.XSHE|[A-Z0-9]{2,}\.(?!(XSHG|XSHE|OFCN)))'
SYMBOL_PATTERN_HS_INDEX = '(\d{6}.ZICN|000\d{3}.XSHG|399\d{3}.XSHE)'
SYMBOL_PATTERN_FUND = '([15]\d{5}\.(XSHE|XSHG)|\d{6}\.OFCN)\d{0,1}'
SYMBOL_PATTERN_EXCHANGE_FUND = '[15]\d{5}\.(XSHE|XSHG)\d{0,1}'
SYMBOL_PATTERN_OTC_FUND = '\d{6}\.OFCN\d{0,1}'
SYMBOL_PATTERN_OPTION = '^(510050[CP]|(m\d{4}-[CP]-|SR\d{3}[CP]))\d{4}'
SYMBOL_PATTERN_NH_FUTURE_INDEX = '[\w]+.NHCI'
SYMBOL_PATTERN_DIGITAL_CURRENCY = '([A-Z]{1,})([\|])([A-Z]{1,})\.([A-Z]{1,})'


STOCK_PATTERN = re.compile(SYMBOL_PATTERN_STOCK)
BASE_FUTURES_PATTERN = re.compile(SYMBOL_PATTERN_BASE_FUTURES)
CONTINUOUS_FUTURES_PATTERN = re.compile(SYMBOL_PATTERN_CONTINUOUS_FUTURES)
INDEX_PATTERN = re.compile(SYMBOL_PATTERN_INDEX)
HS_INDEX_PATTERN = re.compile(SYMBOL_PATTERN_HS_INDEX)
NH_FUTURE_INDEX_PATTERN = re.compile(SYMBOL_PATTERN_NH_FUTURE_INDEX)
FUND_PATTERN = re.compile(SYMBOL_PATTERN_FUND)
XZCE_FUTURES_PATTERN = re.compile('([A-Z]{2})(\d{3})$')
OPTION_PATTERN = re.compile(SYMBOL_PATTERN_OPTION)
DIGITAL_CURRENCY_PATTERN = re.compile(SYMBOL_PATTERN_DIGITAL_CURRENCY)


__all__ = [
    'STOCK_PATTERN',
    'BASE_FUTURES_PATTERN',
    'CONTINUOUS_FUTURES_PATTERN',
    'INDEX_PATTERN',
    'HS_INDEX_PATTERN',
    'NH_FUTURE_INDEX_PATTERN',
    'FUND_PATTERN',
    'XZCE_FUTURES_PATTERN',
    'OPTION_PATTERN',
    'DIGITAL_CURRENCY_PATTERN'
]
